version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: debook-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: debook
      POSTGRES_USER: debook
      POSTGRES_PASSWORD: debook
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: